apiVersion: v1
kind: Service
metadata:
  name: add
  namespace: "30"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: add
  sessionAffinity: None
  type: ClusterIP
