kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: delete-v1-buildconfig
  namespace: '30'
spec:
  output:
    to:
      kind: DockerImage
      name: 'image-registry.openshift-image-registry.svc:5000/30/delete:v1'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'image-registry.openshift-image-registry.svc:5000/openshift/python:3.9-ubi8'
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://gitlab.poc.amc:9443/root/servicemesh-example.git'
    contextDir: /delete_user_app_v1
  runPolicy: Serial
