apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: front-gateway
  namespace: "30"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - front-30.apps.poc.amc
    port:
      name: http
      number: 80
      protocol: HTTP
