apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-service-account-all-list-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali-list
subjects:
- kind: ServiceAccount
  name: kiali-service-account
  namespace: istio-system
